### ISSUE TITLE
Initialization race condition

### ISSUE THREAD

**Issue by bwagstaff** [PlayFab/PlayFabMultiplayerUnreal#22]
When multiple networking libraries are used in a solution, this initialization is a race condition. If other socket subsytems are initialized, the playfab socket subsystem will not initialize.
As a local fix we're adding the condition:
`static_cast<FPlayFabSocketSubsystem*>(ISocketSubsystem::Get(PLAYFAB_SOCKET_SUBSYSTEM)) == nullptr`

https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/7e146a22a4adf81301a89f367756dc0b7c347a4e/Source/Private/OnlineSubsystemPlayFab.cpp#L108

**Comment by nassosterz-ms** [comment]
One thing is that the above if statement as I see it can be simplified as:
`if (!SocketsPlugin.IsValid() || !SocketsPlugin->IsEnabled()))`

I am not quite sure I understand how your added condition helps. Are you saying that the PlayFabSubsystem can be initialized from another networking library?

**Comment by Leonardo-Rocha** [comment]
I believe he's suggesting the following. Changing from:

https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/7e146a22a4adf81301a89f367756dc0b7c347a4e/Source/Private/OnlineSubsystemPlayFab.cpp#L108

To:

```cpp
if (static_cast<FPlayFabSocketSubsystem*>(ISocketSubsystem::Get(PLAYFAB_SOCKET_SUBSYSTEM)) == nullptr)
{
    UE_LOG_ONLINE(Log, TEXT("Initializing PlayFabPartSocketSubsystem"));
    CreatePlayFabSocketSubsystem();
}
```

IMO the original condition doesn't make sense, since this line 
https://github.com/PlayFab/PlayFabMultiplayerUnreal/blob/7e146a22a4adf81301a89f367756dc0b7c347a4e/Source/Private/OnlineSubsystemPlayFab.cpp#L107

actually returns the PlayFabSDK plugin which has no sockets subsystem at all. Maybe it had at some point in the past, but it doesn't work now.
